(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
Handlebars.partials['about'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!--==================== Who we are ====================-->\n<section class=\"add-section space bg-light\" id=\"about-us\">\n    <div class=\"space\">\n        <div class=\"container\">\n            <div class=\"row\">\n                <div class=\"col-md-12\">\n                    <div class=\"center-title\">\n                        <h2>Who we are</h2>\n                    </div>\n                </div>\n            </div>\n            <div class=\"row\">\n                <p>Protege Global Ecommerce (PG-ecom) has trained over 1,200 people in how to launch\n                    and manage successful online businesses. Courses are currently offered in Haitian\n                    Creole to help Haitians learn how to make money online. Course offerings will be expanded to English\n                    soon.\n                </p>\n            </div>\n        </div>\n    </div>\n</section>\n<!--// END of Who we are -->";
},"useData":true});
Handlebars.partials['about_esterling'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!--==================== About ====================-->\n<section class=\"about-us\">\n    <div class=\"container\">\n        <div class=\"row d-flex\">\n            <div class=\"col-md-12 col-lg-7 align-items-center\">\n                <div class=\"testi-content_block\">\n                    <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":7,"column":30},"end":{"line":7,"column":65}}})) != null ? stack1 : "")
    + "/images/quote.png\" class=\"img-fluid\" alt=\"#\">\n                    <h3>Esterling Accime is a software engineer, educator and\n                        entrepreneur with a wealth of knowledge\n                        in digital retailing and e-commerce.</h3>\n                    <span>Esterling Accime</span>\n                    <p>PG-ecom Founder, United States</p>\n                </div>\n            </div>\n        </div>\n    </div>\n    <div class=\"testi-img_wrap\">\n        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":18,"column":18},"end":{"line":18,"column":53}}})) != null ? stack1 : "")
    + "/images/accime_profile.png\" class=\"img-fluid\" alt=\"#\" width=\"650\">\n    </div>\n\n</section>\n<section class=\"add-section content-wrap\">\n    <div class=\"container\">\n        <div class=\"row d-flex\">\n            <p class=\"about-bio\">Esterling founded Protege Global E-commerce (PG-ecom), a skills training organization\n                that creates content and courses around e-commerce. Courses are provided in Haitian Creole\n                to help Haitians launch, create and manage successful online businesses.\n                Esterling is also co-founder of <a href=\"https://ecombrandbuilder.com/\">Ecom Builder</a> that helps\n                customers start\n                their e-commerce business with the right high-conversion creative and assets.\n            </p>\n            <p class=\"about-bio\">Growing up in Haiti, Esterling has a passion for bringing technology to the country.\n                He believes the future of Haiti’s technology landscape is promising if those with the experience\n                and knowledge democratize access. To help connect Haitians with other technology professionals,\n                Esterling co-founded <a href=\"http://tichaiti.dev/\">tichaiti</a> to collectively create solutions that\n                uplift Haiti and the Haitian people.\n            </p>\n        </div>\n    </div>\n</section>\n<!--//END about-us -->";
},"useData":true});
Handlebars.partials['banner'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!-- Main Title -->\n<div class=\"main-title__alt header__bg\">\n    <div class=\"container\">\n        <div class=\"row\">\n            <div class=\"col-md-12 col-lg-6\">\n                <div class=\"hero-title  text-center  text-md-left\">\n                    <h1>Take your business<br>\n                        online.</h1>\n                    <div class=\"add-btn courses-btn_wrap\">\n                        <a href=\"https://courses.pgecom.com/\" class=\"btn btn-primary\">Courses</a>\n                        <!-- <a href=\"https://bit.ly/pg-checkout\" data-toggle=\"modal\" data-target=\"#contactmodal\" class=\"btn btn-primary\">Start now</a> -->\n                    </div>\n                </div>\n            </div>\n            <div class=\"col-md-8\">\n                <div class=\"main-banner_md\">\n                    <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":17,"column":30},"end":{"line":17,"column":65}}})) != null ? stack1 : "")
    + "/images/online_shopping.svg\" class=\"img-fluid\" alt=\"#\">\n                </div>\n            </div>\n        </div>\n    </div>\n    <div class=\"bg-style d-none d-md-block\">\n        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":23,"column":18},"end":{"line":23,"column":53}}})) != null ? stack1 : "")
    + "/images/bg-1.png\" class=\"img-fluid\" alt=\"#\">\n    </div>\n</div>";
},"useData":true});
Handlebars.partials['book_esterling_now'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!--==================== ADD ====================-->\n<section class=\"add-section clearfix collapse-wrap\">\n    <div class=\"container\">\n        <div class=\"row justify-content-center\">\n            <div class=\"col-md-10\">\n                <div class=\"add-box\">\n                    <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":7,"column":30},"end":{"line":7,"column":65}}})) != null ? stack1 : "")
    + "/images/shield-green.svg\" class=\"img-fluid shield\" alt=\"Check mark\">\n                    <div class=\"add-content\">\n                        <h3> Book Esterling Accime now</h3>\n                        <p>Software engineer, educator and entrepreneur with a wealth of knowledge in digital retailing\n                            and e-commerce.</p>\n                    </div>\n                    <div class=\"add-btn\">\n                        <a href=\"https://calendly.com/accimeesterlin/speaking\" class=\"btn btn-primary\">Book now</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</section>";
},"useData":true});
Handlebars.partials['courses'] = template({"1":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.lambda, alias3=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "            <div class=\"col-md-4\">\n                <div class=\"row courses-element\">\n                    <div class=\"courses-block\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(2, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":15,"column":34},"end":{"line":15,"column":67}}})) != null ? stack1 : "")
    + alias3(alias2((depth0 != null ? lookupProperty(depth0,"image_url") : depth0), depth0))
    + "\" alt=\"\" />\n                        <p><b>"
    + alias3(alias2((depth0 != null ? lookupProperty(depth0,"course_name") : depth0), depth0))
    + "</b></p>\n                        <p><b>"
    + alias3(alias2((depth0 != null ? lookupProperty(depth0,"language") : depth0), depth0))
    + "</b></p>\n                        <p>"
    + alias3(((helper = (helper = lookupProperty(helpers,"description") || (depth0 != null ? lookupProperty(depth0,"description") : depth0)) != null ? helper : container.hooks.helperMissing),(typeof helper === "function" ? helper.call(alias1,{"name":"description","hash":{},"data":data,"loc":{"start":{"line":18,"column":27},"end":{"line":18,"column":42}}}) : helper)))
    + "</p>\n\n                        <div class=\"add-btn courses-btn_wrap\">\n                            <a href=\""
    + alias3(alias2((depth0 != null ? lookupProperty(depth0,"start_url") : depth0), depth0))
    + "\" class=\"btn btn-primary\">\n                                Start now\n                            </a>\n                            <a href=\""
    + alias3(alias2((depth0 != null ? lookupProperty(depth0,"curriculum_url") : depth0), depth0))
    + "\"\n                                class=\"btn btn-primary\">\n                                View curriculum\n                            </a>\n                        </div>\n                    </div>\n                </div>\n            </div>\n\n";
},"2":function(container,depth0,helpers,partials,data) {
    return "";
},"4":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<section class=\"courses\" id=\"courses\">\n    <div class=\"container\">\n        <div class=\"row\">\n            <div class=\"col-md-12\">\n                <div class=\"center-title\">\n                    <h2>Courses</h2>\n                </div>\n            </div>\n        </div>\n        <div class=\"row courses-wrap\">\n"
    + ((stack1 = lookupProperty(helpers,"each").call(alias1,(depth0 != null ? lookupProperty(depth0,"list_courses") : depth0),{"name":"each","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":11,"column":12},"end":{"line":33,"column":21}}})) != null ? stack1 : "")
    + "\n        </div>\n    </div>\n    <div class=\"courses-bg courses-bg_secong\">\n        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(4, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":38,"column":18},"end":{"line":38,"column":53}}})) != null ? stack1 : "")
    + "/images/bg-image4.png\" class=\"img-fluid\" alt=\"#\" />\n    </div>\n</section>";
},"useData":true});
Handlebars.partials['ecommerce'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!--==================== NEW INSURANCE ====================-->\n<div class=\"space bg-image\">\n    <div class=\"container\">\n        <div class=\"row\">\n            <div class=\"col-md-12\">\n                <div class=\"center-title\">\n                    <h2>E-commerce</h2>\n                </div>\n            </div>\n        </div>\n        <div class=\"row\">\n            <div class=\"col-md-12 col-lg-7 ml-auto\">\n                <div class=\"insurance-title_wrap insurance-title_wrap2\">\n                    <p class=\"insurance-para\">2020 was the year that projected e-commerce into our everyday lives.\n                        More and more people are shopping and buying online.\n                        In the U.S. alone, e-commerce sales are projected to hit more than $700 billion in 2020,\n                        and global e-commerce sales are expected to reach $4.2 trillion according to Shopify.\n                    </p>\n                    <p>Now is the time to start your online business. </p>\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":21,"column":34},"end":{"line":21,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>It’s more than just having a nice website</h6>\n                            <p>Your website and strategy needs to cut through the noise, get noticed and attract\n                                customers.</p>\n                        </div>\n                    </div>\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":29,"column":34},"end":{"line":29,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Finding the right supplier</h6>\n                            <p>You might have a great idea and an endless source of website traffic,\n                                but if your manufacturer can’t keep up with demand, or if the quality of the product\n                                they are producing is subpar, you won’t be in business long.\n                            </p>\n                            <p>Targeting the right customer on the right device at the right moment can be challenging -\n                                it all comes down to your advertising and marketing strategy.\n                            </p>\n                        </div>\n                    </div>\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":42,"column":34},"end":{"line":42,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Target the right audience</h6>\n                            <p>Target the right person on the right device at the right moment can be challenging</p>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n    <div class=\"banner-img-3\">\n        <img src=\"./"
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":53,"column":20},"end":{"line":53,"column":55}}})) != null ? stack1 : "")
    + "/images/teamwork.svg\" width=\"680\" class=\"img-fluid\" alt=\"#\">\n    </div>\n    <div class=\"bg-style2\">\n        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":56,"column":18},"end":{"line":56,"column":53}}})) != null ? stack1 : "")
    + "/images/bg-2.png\" class=\"img-fluid\" alt=\"#\">\n    </div>\n</div>\n<!--//END NEW INSURANCE -->";
},"useData":true});
Handlebars.partials['faqs'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!--==================== FAQS SECTION ====================-->\n<section class=\"content-wrap\" id=\"faqs\">\n    <div class=\"container\">\n        <div class=\"row\">\n            <div class=\"col-md-12\">\n                <div class=\"center-title\">\n                    <h2>FAQs</h2>\n                </div>\n            </div>\n        </div>\n        <div class=\"row\">\n            <div class=\"col-md-6\">\n                <div class=\"content-box content-box1\">\n                    <h5>Can I watch the lessons on my phone?</h5>\n                    <p>Yes you can watch it on your phone. Navigate via the class url, and login to the assigned courses\n                    </p>\n                </div>\n                <div class=\"content-box\">\n                    <h5>How is the material available online?</h5>\n                    <p>Online classes are delivered using a learning management system, called Teachable.\n                        Students log into Teachable and can select their course sites.\n                        Once a student is in their course site, they can access lectures,\n                        PowerPoint, assignments, readings, documents, videos, links, comments, etc\n                    </p>\n                </div>\n            </div>\n            <div class=\"col-md-6\">\n                <div class=\"content-box content-box1\">\n                    <h5>Are online classes self-paced or scheduled?</h5>\n                    <p>The programs are self-paced or independent study.</p>\n                </div>\n                <div class=\"content-box\">\n                    <h5>Can I go on vacation while taking an online class?</h5>\n                    <p>Online courses require weekly logins and weekly assignment submissions.\n                        Students must ensure they are able to meet the course requirements throughout\n                        the duration of the semester.\n                    </p>\n                </div>\n            </div>\n        </div>\n    </div>\n</section>\n<!--//END FAQS SECTION -->";
},"useData":true});
Handlebars.partials['footer'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<footer>\n    <div class=\"container\">\n        <div class=\"row\">\n            <div class=\"col-md-3\">\n                <div class=\"footer-title\">\n                    <h6>ADDRESS</h6>\n                    <p>PO BOX 767398, Roswell, GA 30076<br>\n                        <a href=\"https://wa.me/14049997045\">+1 (404) 999 7045</a><br>\n                        <a href=\"mailto:info@pgecom.com\">info@pgecom.com</a>\n                    </p>\n                </div>\n            </div>\n            <div class=\"col-md-3\">\n                <div class=\"footer-title\">\n                    <h6>FOLLOW US</h6>\n                    <ul>\n                        <li><a href=\"https://www.facebook.com/pgecom\">Facebook</a></li>\n                        <li><a href=\"https://www.youtube.com/channel/UCkg2EsiO2FASY3ZBlPIcI-g\">YouTube</a></li>\n                        <li><a href=\"https://twitter.com/pgecommerce\">Twitter</a></li>\n                        <li><a href=\"https://www.instagram.com/pgecom/\">Instagram</a></li>\n                        <li><a href=\"https://help.pgecom.com/\">Help</a></li>\n                        <li><a href=\"https://t.me/+Up2dG_v6cnJ9yshe\">Telegram Group</a></li>\n                        <li><a href=\"https://chat.whatsapp.com/GGfyVzp9jxa0Ap08tfecpM\">Whatsapp Group</a></li>\n                        <li><a href=\"https://www.facebook.com/groups/196555738106924\">Facebook Group</a></li>\n                    </ul>\n                </div>\n            </div>\n\n            <div class=\"col-md-3\">\n                <div class=\"footer-title\">\n                    <h6>POLICIES</h6>\n                    <ul>\n                        <li><a href=\"./refund-policy\">Refund Policy</a></li>\n                        <li><a href=\"./terms-policy\">Terms of Service</a></li>\n                        <li><a href=\"./privacy-policy\">Privacy Policy</a></li>\n                    </ul>\n                </div>\n            </div>\n            <div class=\"col-md-3\">\n                <div class=\"footer-title\">\n                    <h6>ABOUT US</h6>\n                    <p>Protege Global Ecommerce (PG-ecom) has trained over 1,200 people in how to launch and manage\n                        successful online businesses.\n                    </p>\n                </div>\n            </div>\n        </div>\n        <div class=\"row\">\n            <div class=\"col-md-12\">\n                <div class=\"copyright\">\n                    <p>Copyright © 2021. Protege Global Ecommerce, INC</p>\n                </div>\n            </div>\n        </div>\n    </div>\n</footer>";
},"useData":true});
Handlebars.partials['header'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<header>\n"
    + ((stack1 = container.invokePartial(lookupProperty(partials,"navbar"),depth0,{"name":"navbar","data":data,"indent":"    ","helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + ((stack1 = container.invokePartial(lookupProperty(partials,"banner"),depth0,{"name":"banner","data":data,"indent":"    ","helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + ((stack1 = container.invokePartial(lookupProperty(partials,"modals"),depth0,{"name":"modals","data":data,"indent":"    ","helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + ((stack1 = container.invokePartial(lookupProperty(partials,"ecommerce"),depth0,{"name":"ecommerce","data":data,"indent":"    ","helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + "</header>";
},"usePartial":true,"useData":true});
Handlebars.partials['modals'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!--  Contact Modal -->\n<div class=\"modal fade\" id=\"contactmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"phpcontactform\"\n    aria-hidden=\"true\">\n    <div class=\"modal-dialog modal-dialog-centered modal-dialog-zoom\" role=\"document\">\n        <div class=\"modal-content\">\n\n            <div class=\"modal-body\">\n\n                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n                    <span aria-hidden=\"true\">×</span>\n                </button>\n\n                <form class=\"quote-form\" action=\"php/contact.php\" method=\"post\" id=\"phpcontactform\">\n                    <h5 class=\"text-center mt-3 mb-4\">Start the course now!</h5>\n                    <div class=\"form-group\">\n                        <div class=\"row\">\n                            <div class=\"col-sm-6\"> <input type=\"text\" class=\"form-control\" id=\"first_name\"\n                                    name=\"first_name\" placeholder=\"First Name*\" required> </div>\n                            <div class=\"col-sm-6\"> <input type=\"text\" class=\"form-control\" id=\"last_name\"\n                                    name=\"last_name\" placeholder=\"Last Name*\" required> </div>\n                        </div>\n                    </div>\n                    <div class=\"form-group\">\n                        <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email Address*\"\n                            required>\n                    </div>\n                    <div class=\"form-group\">\n                        <input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\" placeholder=\"Phone*\" required>\n                    </div>\n                    <div class=\"form-group\">\n                        <input type=\"text\" class=\"form-control\" id=\"pac-input\" name=\"address\" placeholder=\"Address*\"\n                            required>\n                    </div>\n                    <button type=\"submit\" class=\"btn btn-primary w-100\" id=\"js-contact-btn\"><strong>\n                            Start the course now!\n                        </strong> </button>\n                    <div id=\"js-contact-result\" data-success-msg=\"Success, We will get back to you soon\"\n                        data-error-msg=\"Oops! Something went wrong\"></div>\n\n                </form>\n\n\n            </div>\n\n        </div>\n    </div>\n</div>\n<!--  // Contact Modal -->";
},"useData":true});
Handlebars.partials['navbar'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"3":function(container,depth0,helpers,partials,data) {
    return "active";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!-- Navbar -->\n<div class=\"nav-menu\">\n  <div class=\"container\">\n    <div class=\"row\">\n      <div class=\"col-md-12\">\n        <nav class=\"navbar navbar-expand-lg navbar-light\">\n          <a class=\"navbar-brand\" href=\"/\">\n            <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":8,"column":22},"end":{"line":8,"column":57}}})) != null ? stack1 : "")
    + "/images/pg-logo.png\" alt=\"PG-ecom Logo\" />\n          </a>\n          <button class=\"navbar-toggler navbar-toggler_second\" type=\"button\" data-toggle=\"collapse\"\n            data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n            aria-label=\"Toggle navigation\">\n            <i class=\"fas fa-bars\"></i>\n            <!--  <span class=\"navbar-toggler-icon\"></span> -->\n          </button>\n          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n            <ul class=\"navbar-nav ml-auto\">\n              <!-- <li class=\"nav-item\">\n                                    <a class=\"nav-link\" href=\"tel:+16785048981\" tabindex=\"-1\" aria-disabled=\"true\">+1 678 504-8981</a>\n                                </li> -->\n              <li class=\"nav-item "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":21,"column":34},"end":{"line":21,"column":65}}})) != null ? stack1 : "")
    + "\">\n                <a class=\"nav-link\" href=\"/\" tabindex=\"-1\" aria-disabled=\"true\">\n                  Home\n                </a>\n              </li>\n              <li class=\"nav-item "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageCourses") : depth0),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":26,"column":34},"end":{"line":26,"column":68}}})) != null ? stack1 : "")
    + "\">\n                <a class=\"nav-link\" href=\"/courses\" tabindex=\"-1\" aria-disabled=\"true\">\n                  Courses\n                </a>\n              </li>\n              <li class=\"nav-item "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageCourses") : depth0),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":31,"column":34},"end":{"line":31,"column":68}}})) != null ? stack1 : "")
    + "\">\n                <a class=\"nav-link\" href=\"https://perks.pgecom.com\" tabindex=\"-1\" aria-disabled=\"true\">\n                  Perks\n                </a>\n              </li>\n              <li class=\"nav-item "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageCourses") : depth0),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":36,"column":34},"end":{"line":36,"column":68}}})) != null ? stack1 : "")
    + "\">\n                <a class=\"nav-link\" href=\"https://store.pgecom.com\" tabindex=\"-1\" aria-disabled=\"true\">\n                  Store\n                </a>\n              </li>\n              <li class=\"nav-item "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageFaqs") : depth0),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":41,"column":34},"end":{"line":41,"column":65}}})) != null ? stack1 : "")
    + "\">\n                <a class=\"nav-link\" href=\"/faqs\" tabindex=\"-1\" aria-disabled=\"true\">\n                  FAQs\n                </a>\n              </li>\n              <li class=\"nav-item "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageAboutUs") : depth0),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":46,"column":34},"end":{"line":46,"column":68}}})) != null ? stack1 : "")
    + "\">\n                <a class=\"nav-link\" href=\"/about\" tabindex=\"-1\" aria-disabled=\"true\">\n                  About Us\n                </a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\"\n                  href=\"https://sso.teachable.com/secure/583714/users/sign_up?reset_purchase_session=1\" tabindex=\"-1\"\n                  aria-disabled=\"true\">\n                  Sign Up\n                </a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\"\n                  href=\"https://sso.teachable.com/secure/583714/users/sign_in?reset_purchase_session=1\" tabindex=\"-1\"\n                  aria-disabled=\"true\">\n                  Login\n                </a>\n              </li>\n            </ul>\n          </div>\n        </nav>\n      </div>\n    </div>\n  </div>\n</div>\n<!--//END NEW INSURANCE -->";
},"useData":true});
Handlebars.partials['past_speaking_and_training'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!--==================== Past Speaking and Training ====================-->\n<section class=\"add-section clearfix collaps-wrap\">\n    <div class=\"space\">\n        <div class=\"container\">\n            <div class=\"row\">\n                <div class=\"col-md-12\">\n                    <div class=\"center-title\">\n                        <h2>Past Speaking & Training</h2>\n                    </div>\n                </div>\n            </div>\n            <div class=\"row\">\n                <div class=\"past-speaking-engagement insurance-title_wrap insurance-title_wrap2\">\n                    <p class=\"insurance-para\">Esterling has been a speaker at the following conferences and events: </p>\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":16,"column":34},"end":{"line":16,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Haiti Tourism Innovation Summit</h6>\n                            <p><a href=\"https://www.tourisminnovationsummit.com/\">Tourism Innovation Summit</a>, a\n                                community of Tourism leaders with a clear vision and plan to impact the tourism industry\n                                in the Caribbean Region, especially Haiti.</p>\n                        </div>\n                    </div>\n\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":26,"column":34},"end":{"line":26,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Trilogy Annual Conference</h6>\n                            <p><a href=\"https://www.trilogyed.com/\">Trilogy Education</a> is a Workforce Accelerator.\n                                They partner with the best universities in the world\n                                to create and manage skills-based training programs. Together, they’re training today’s\n                                workers\n                                with tomorrow’s skills to help companies bridge the digital skills gap.\n                            </p>\n                        </div>\n                    </div>\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":38,"column":34},"end":{"line":38,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Startup Grind</h6>\n                            <p><a href=\"https://www.startupgrind.com/jeremie/\">Startup Grind</a> is a global startup\n                                community designed to educate inspire and connect more entrepreneurs.</p>\n                        </div>\n                    </div>\n\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":47,"column":34},"end":{"line":47,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Caribbean Ecommerce Workshop in the Dominican Republic</h6>\n                            <p>Walk in without a business, walk out with a business.\n                                The <a href=\"https://youtu.be/IVR-Pp5Ns7M\">2020 workshop</a> has concluded and was a\n                                success. Stay tuned for 2021 dates.\n                            </p>\n                        </div>\n                    </div>\n\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":58,"column":34},"end":{"line":58,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Haiti Coding Workshop</h6>\n                            <p>Learn the fundamentals of full-stack development in two days.\n                                Receive the tools and support to continue to learn and expand your skills beyond the\n                                workshop.\n                                The <a\n                                    href=\"https://www.trilogyed.com/blog/bringing-learning-home-how-one-coding-grad-is-making-a-difference-in-haiti/\">2018\n                                    workshop</a> concluded and was a success. Stay tuned for future dates.\n                            </p>\n                        </div>\n                    </div>\n\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":72,"column":34},"end":{"line":72,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Render ATL (2021)</h6>\n                            <p><a href=\"https://www.renderatl.com/\">RenderATL</a> is the first major React conference in\n                                the Southern United States.\n                                Conceived by a team of passionate React engineers who're looking to help drive.\n                            </p>\n                        </div>\n                    </div>\n\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":83,"column":34},"end":{"line":83,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>React ATL</h6>\n                            <p><a href=\"https://www.meetup.com/en-AU/React-ATL/\">React ATL</a> is a monthly developer\n                                meetup to discuss trends and tools coming out of the ReactJS ecosystem.\n                        </div>\n                    </div>\n\n                    <div class=\"insurance-type d-flex align-items-center\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":92,"column":34},"end":{"line":92,"column":69}}})) != null ? stack1 : "")
    + "/images/tick.png\" alt=\"Check mark\">\n                        <div class=\"insurance-type_title\">\n                            <h6>Georgia Tech events and meetups</h6>\n                            <p> <a href=\"https://www.meetup.com/Tech-Full-Stack-Web-Developers/\">Full Stack\n                                    Developers</a> (alumni of Georgia Tech Coding Boot Camp Program) working to continue\n                                their networking activities and establish connection.\n                            </p>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n\n</section>\n<!-- End of Past Speaking and Training -->";
},"useData":true});
Handlebars.partials['satisfaction_guarantee'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!--==================== Satisfaction Guarantee ====================-->\n<section class=\"add-section clearfix\">\n    <div class=\"container\">\n        <div class=\"row justify-content-center\">\n            <div class=\"col-md-10\">\n                <div class=\"add-box\">\n                    <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":7,"column":30},"end":{"line":7,"column":65}}})) != null ? stack1 : "")
    + "/images/shield-yellow.svg\" class=\"img-fluid shield\" alt=\"#\">\n                    <div class=\"add-content\">\n                        <h3> 100% Satisfaction Guarantee</h3>\n                        <p>We offer a no questions asked refund policy for 7 days from the purchase date</p>\n                    </div>\n                    <div class=\"add-btn\">\n                        <a href=\"https://courses.pgecom.com/\" class=\"btn btn-primary\">Courses</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</section>\n<!--//END ADD -->";
},"useData":true});
Handlebars.partials['start_bussiness'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!--==================== Start your online business ====================-->\n<section class=\"add-section clearfix collapse-wrap\">\n    <div class=\"container\">\n        <div class=\"row justify-content-center\">\n            <div class=\"col-md-10\">\n                <div class=\"add-box\">\n                    <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":7,"column":30},"end":{"line":7,"column":65}}})) != null ? stack1 : "")
    + "/images/shield-green.svg\" class=\"img-fluid shield\" alt=\"#\">\n                    <div class=\"add-content\">\n                        <h3> Start your online business</h3>\n                        <p>PG-ecom is here to teach you the ins and outs of a successful e-commerce business. </p>\n                    </div>\n                    <div class=\"add-btn\">\n                        <a href=\"https://courses.pgecom.com/\" class=\"btn btn-primary\">Courses</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n</section>";
},"useData":true});
Handlebars.partials['steps_to_launch_business'] = template({"1":function(container,depth0,helpers,partials,data) {
    return "..";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!--==================== Steps to launching your online business ====================-->\n<section class=\"space bg-light\">\n    <div class=\"container\">\n        <div class=\"row\">\n            <div class=\"col-md-12\">\n                <div class=\"center-title\">\n                    <h2>Steps to launching your online business</h2>\n                </div>\n            </div>\n        </div>\n        <div class=\"row\">\n            <div class=\"col-md-6 col-lg-4\">\n                <div class=\"item-box\">\n                    <div class=\"item-icon color1\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":15,"column":34},"end":{"line":15,"column":69}}})) != null ? stack1 : "")
    + "/images/tshirt-solid.svg\" class=\"img-fluid\" alt=\"#\">\n                    </div>\n                    <h6>Find a high-potential product</h6>\n                    <p>Find something that has a large global demand, high margins and can be easily warehoused and\n                        fulfilled.</p>\n                </div>\n            </div>\n            <div class=\"col-md-6 col-lg-4\">\n                <div class=\"item-box\">\n                    <div class=\"item-icon color1\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":25,"column":34},"end":{"line":25,"column":69}}})) != null ? stack1 : "")
    + "/images/warehouse-solid.svg\" class=\"img-fluid\" alt=\"#\">\n                    </div>\n                    <h6>Lock down a manufacturer</h6>\n                    <p>You need a manufacturer who can keep up with demand and creates a quality product.</p>\n                </div>\n            </div>\n            <div class=\"col-md-6 col-lg-4\">\n                <div class=\"item-box\">\n                    <div class=\"item-icon color2\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":34,"column":34},"end":{"line":34,"column":69}}})) != null ? stack1 : "")
    + "/images/social-media.svg\" class=\"img-fluid\" alt=\"#\">\n                    </div>\n                    <h6>Choose a brand name and secure your online presence</h6>\n                    <p>Your brand name needs to be not only memorable and appealing to your target audience,\n                        but it also needs to be available in the form of a domain name and social media handles.\n                    </p>\n                </div>\n            </div>\n            <div class=\"col-md-6 col-lg-4\">\n                <div class=\"item-box\">\n                    <div class=\"item-icon color3\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":45,"column":34},"end":{"line":45,"column":69}}})) != null ? stack1 : "")
    + "/images/laptop-solid.svg\" class=\"img-fluid\" alt=\"#\">\n                    </div>\n                    <h6>Develop your website</h6>\n                    <p>Shopify is a great choice for those who don’t have the technical know-how or budget to create a\n                        custom website.</p>\n                </div>\n            </div>\n            <div class=\"col-md-6 col-lg-4\">\n                <div class=\"item-box\">\n                    <div class=\"item-icon color4\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":55,"column":34},"end":{"line":55,"column":69}}})) != null ? stack1 : "")
    + "/images/lightbulb-regular.svg\" class=\"img-fluid\" alt=\"#\">\n                    </div>\n                    <h6>Create a marketing plan</h6>\n                    <p>You have a product and a website, now you need to put your offering\n                        in front of consumers who are likely to be interested in the product.\n                    </p>\n                </div>\n            </div>\n            <div class=\"col-md-6 col-lg-4\">\n                <div class=\"item-box\">\n                    <div class=\"item-icon color5\">\n                        <img src=\""
    + ((stack1 = lookupProperty(helpers,"unless").call(alias1,(depth0 != null ? lookupProperty(depth0,"isPageHome") : depth0),{"name":"unless","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":66,"column":34},"end":{"line":66,"column":69}}})) != null ? stack1 : "")
    + "/images/store-solid.svg\" class=\"img-fluid\" alt=\"#\">\n                    </div>\n                    <h6>Launch your online store</h6>\n                    <p>Do not wait until you think it’s perfect to launch.\n                        You will need to continually split-test and make changes -- your e-commerce business\n                        will always be growing and evolving.\n                    </p>\n                </div>\n            </div>\n        </div>\n    </div>\n</section>\n<!-- End of steps -->";
},"useData":true});
Handlebars.partials['training'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!--==================== Training SECTION ====================-->\n<section class=\"add-section content-wrap\">\n    <div class=\"space\">\n        <div class=\"container\">\n            <div class=\"row\">\n                <div class=\"col-md-12\">\n                    <div class=\"center-title\">\n                        <h2>Training</h2>\n                    </div>\n                </div>\n            </div>\n            <div class=\"row p-20\">\n                <p>Esterling Accime is an experienced speaker and teacher.\n                    He was an instructor at the Georgia Tech Coding Boot Camp where he taught full stack web\n                    development.\n                    He has also spoken at conferences about how to start and manage a successful e-commerce business.\n                </p>\n                <div class=\"ea-training\">\n                    <p>Esterling can speak to your group or organization about the following:</p> <br>\n                    <div class=\"courses-text\">\n                        <i class=\"fas fa-check\"></i>\n                        <p>Facebook advertising for small businesses</p>\n                    </div>\n                    <div class=\"courses-text\">\n                        <i class=\"fas fa-check\"></i>\n                        <p>Tools for successful online businesses</p>\n                    </div>\n                    <div class=\"courses-text\">\n                        <i class=\"fas fa-check\"></i>\n                        <p>Shopify</p>\n                    </div>\n                    <div class=\"courses-text\">\n                        <i class=\"fas fa-check\"></i>\n                        <p>WooCommerce</p>\n                    </div>\n                    <div class=\"courses-text\">\n                        <i class=\"fas fa-check\"></i>\n                        <p>Dropshipping</p>\n                    </div>\n                    <p>Send a message to <a href=\"mailto:info@pgecom.com\">info@pgecom.com</a> for information,\n                        scheduling and pricing.</p>\n                </div>\n            </div>\n        </div>\n    </div>\n\n</section>";
},"useData":true});
})();